export const CARD_SIZE = 132
export const CARD_GAP = 18
export const SLOT = CARD_SIZE + CARD_GAP
export const REEL_LENGTH = 56
export const CENTER_INDEX = 46
export const VIEWPORT_HEIGHT = 620
export const SPIN_MS = 4800
export const OPEN_MS = 700
export const REEL_WIDTH = CARD_SIZE + 40
